[server]
address = "127.0.0.1"
maxUploadSize = 1
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#176C53"
backgroundColor = "#FAFAF7"
secondaryBackgroundColor = "#F0F3EE"
textColor = "#20352D"
font = "sans serif"

